version: '3'
services:
  flask:
    build: .
    command: python mock_json_flask.py
    volumes:
      - /mock_flask:/data
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2000M
    restart: always
    container_name: flask-a
